### Registration
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
  "username": "test_user_58",
  "email": "user55@example.com",
  "password": "password123"
}

### Working Login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "securepassword"
}


### Getting Activities
GET http://localhost:3000/activities HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwOTYyNzU5NSwiZXhwIjoxNzA5NjMxMTk1fQ.o3s85ZytiPMGuWCERQpo0IfZDFnh6i4zteQ75T7GNR4


### Setting Activities
PATCH http://localhost:3000/activities/1/toggle HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwOTYyNzU5NSwiZXhwIjoxNzA5NjMxMTk1fQ.o3s85ZytiPMGuWCERQpo0IfZDFnh6i4zteQ75T7GNR4

{
  "on": true
}